In [1]:
import pandas as pd
import numpy as np
import forms

In [2]:
df = pd.DataFrame(np.random.randint(0, 100, size=(2000,10000)))
forms.to_spreadsheet_view(df)

,A,B,C,D,E,F,G,H,I,J,...,NTG,NTH,NTI,NTJ,NTK,NTL,NTM,NTN,NTO,NTP
1,21,70,99,27,91,90,29,95,27,66,...,82,41,27,5,81,28,74,2,27,72
2,0,2,52,82,61,58,51,94,23,49,...,74,10,57,41,61,2,91,46,37,67
3,49,15,99,62,22,57,85,84,34,98,...,22,93,40,35,16,95,86,73,12,48
4,74,99,46,99,70,86,13,51,43,62,...,72,2,39,48,83,5,26,20,3,87
5,98,3,20,62,15,74,88,19,94,26,...,55,78,92,14,15,58,12,37,1,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,82,54,23,50,48,98,96,66,44,55,...,53,37,16,92,50,92,63,27,60,76
1997,64,51,58,23,96,58,97,23,30,12,...,37,1,56,30,55,45,84,11,65,62
1998,41,62,32,72,87,66,82,29,39,29,...,7,66,16,38,50,52,61,11,93,27
1999,11,15,21,70,16,81,76,6,33,51,...,76,80,86,47,19,37,52,19,30,28
2000,9,45,61,70,64,34,9,40,82,9,...,98,47,41,67,52,78,29,17,81,1

In [3]:
df2 = pd.DataFrame(np.random.randint(0, 100, size=(100, 4)))
df2.columns = ['This', 'is', 'a', 'test']
forms.to_spreadsheet_view(df2, keep_original_labels=True)

     A (This)  B (is)  C (a)  D (test)
1           6      73     31        28
2          44      22     56        94
3           0      66      6        40
4           2      47     96        58
5          78       1     55        31
..        ...     ...    ...       ...
96         94      32     84         4
97         91      94     50        21
98         81      96     32        14
99         96      91     78        75
100        10      84     52        60

[100 rows x 4 columns]

In [5]:
index = pd.MultiIndex.from_product([['CS168', 'ENGIN120', 'CS194'],
                                  ['BAMPFA', 'Birge', 'Dwinelle']],
                                 names=['Class', 'Room'])
col = pd.MultiIndex.from_product([['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                                  ['101', '102', '103', '104', '105']],
                                 names=['Lecture', 'Section'])
df3 = pd.DataFrame(np.random.randint(0, 100), index, col)
forms.to_spreadsheet_view(df3, keep_original_labels=True)

,"A (('Monday', '101'))","B (('Monday', '102'))","C (('Monday', '103'))","D (('Monday', '104'))","E (('Monday', '105'))","F (('Tuesday', '101'))","G (('Tuesday', '102'))","H (('Tuesday', '103'))","I (('Tuesday', '104'))","J (('Tuesday', '105'))",...,"P (('Thursday', '101'))","Q (('Thursday', '102'))","R (('Thursday', '103'))","S (('Thursday', '104'))","T (('Thursday', '105'))","U (('Friday', '101'))","V (('Friday', '102'))","W (('Friday', '103'))","X (('Friday', '104'))","Y (('Friday', '105'))"
1,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
2,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
3,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
4,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
5,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
6,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
7,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
8,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66
9,66,66,66,66,66,66,66,66,66,66,...,66,66,66,66,66,66,66,66,66,66